Feat/#11 기념일 생성 페이지 화면 구현
2022Letters/frontend pull request #17
Opened 2022-06-29 12:40 UTC by Eunyeol-Lucas

## :white_check_mark:체크리스트
- [x] 페이지 이동
  - /main 페이지에서 (+) 버튼 클릭시 /create 페이지로 이동
- [x] 제목 입력 
  - 글자수 15자로 제한
- [x] 카테고리 
  - default category를 생일로 지정
- [x] 날짜 선택
  -  react-datepicker 라이브러리 사용 날짜 선택
- [x] 게시글 공개 여부
  - input checkbox 활용하여 toggle 버튼 구현

2022-06-29 15:56 UTC, hanyoonseok requested changes
- 개인적으로 우측 하단의 + 버튼이 조금만 더 왼쪽위로 올라와도 될 것 같습니다..! 
- package.json에서 react-google-login 지워주세요.
- 게시글 작성시 날짜 부분을 클릭할 수 있는 요소처럼 보이게 하는게 좋을 것 같아요. 테두리 입체감을 준다던지 혹은 달력 아이콘을 넣는다던지 하는 방식으로요!
- 달력이 나왔을 때 화면을 클릭하면 달력이 닫히도록 하는게 좋을 것 같습니다
- 게시글 공개여부 체크시 색깔 변경을 통해 시각적으로도 표현이 되었으면 좋겠어요

2022-06-29 15:58 UTC, yoon828 requested changes
- 기념일 제목 input창에서 preventDefault 거는게 좋을 것 같습니다! 엔터 누르면 새로고침 돼요
- main에서 + 버튼을 스크롤바에 딱 붙어있는것 보다 좀 더 왼쪽에 두면 좋을 것 같아요

2022-06-30 02:13 UTC, Eunyeol-Lucas commented
> 개인적으로 우측 하단의 + 버튼이 조금만 더 왼쪽위로 올라와도 될 것 같습니다..!
package.json에서 react-google-login 지워주세요.
게시글 작성시 날짜 부분을 클릭할 수 있는 요소처럼 보이게 하는게 좋을 것 같아요. 테두리 입체감을 준다던지 혹은 달력 아이콘을 넣는다던지 하는 방식으로요!
달력이 나왔을 때 화면을 클릭하면 달력이 닫히도록 하는게 좋을 것 같습니다
게시글 공개여부 체크시 색깔 변경을 통해 시각적으로도 표현이 되었으면 좋겠어요

1. 우선 왼쪽으로 위치 조정을 했고, 버튼이 카드 컴포넌트와 위치가 좀 겹처서 추후에 상향 위치 조종 해보겠습니다.
2. 지웠어요~
3. 달력 표시 svg를 넣었습니다. 버튼이 더 나은지 확인부탁드릴게요
4. 카테고리 버튼 활성화와 동일하게 색상 변경했습니다~

2022-06-30 02:13 UTC, Eunyeol-Lucas commented
> 기념일 제목 input창에서 preventDefault 거는게 좋을 것 같습니다! 엔터 누르면 새로고침 돼요
main에서 + 버튼을 스크롤바에 딱 붙어있는것 보다 좀 더 왼쪽에 두면 좋을 것 같아요

수정했습니다!

2022-06-30 03:05 UTC, hanyoonseok commented
- 공개/비공개 전환 속도가 조금 더 빨랐으면 좋겠습니다!
- 빈 제목을 입력해도 넘어가는 것 같아서 `required` 추가하면 좋겠습니다!

2022-06-30 03:52 UTC, yoon828 commented
> * 공개/비공개 버튼 전환 속도가 조금 더 빨랐으면 좋겠습니다!
> * 빈 제목을 입력해도 넘어가는 것 같아서 `required` 추가하면 좋겠습니다!

엇 저는 개인적으로는 토글 속도 괜찮다고 생각합니다..!

2022-06-30 03:52 UTC, yoon828 approved these changes

2022-06-30 08:06 UTC, Eunyeol-Lucas commented
> 공개/비공개 버튼 전환 속도가 조금 더 빨랐으면 좋겠습니다!
빈 제목을 입력해도 넘어가는 것 같아서 required 추가하면 좋겠습니다!

form 태그를 사용해서 input 공란시 required 메시지가 나타나게 하고, 카테고리에 default 값을 없애서 input enter시 category가 공란일 경우 메시지와 함께 submit이 작동하지 않도록 했습니다~

2022-06-30 11:38 UTC, hanyoonseok approved these changes

2022-06-30 11:38 UTC, merged