Feat/#16
2022Letters/frontend pull request #20
Opened 2022-07-01 06:44 UTC by hanyoonseok

guesthome 테스트시 `http://localhost:3000/1` 로 접속해서 테스트 부탁드립니다.

### 테스트내용
- [x] 시작부터 완료까지의 전체적인 플로우
- [x] 꽃 화면 배치 기능
- [x] 꽃 화면 레이아웃 벗어남 방지
- [x] 웹 버전, 모바일 버전 상호호환

2022-07-01 07:42 UTC, yoon828 requested changes
- 꽃 선택하는 화면에서 꽃을 포함하는 div의 크기를 고정시키는게 어떨까요? 그리고 div간의 상하좌우 간격도 일정하면 좋을 것 같습니다.
- 꽃 배치할 때 처음 위치를 왼쪽 상단이 아닌 중앙에 배치하는게 좋을 것 같습니다
- pc버전에서 꽃 이동할 때 모바일 버전과는 다르게 잔상이 남는데 모바일 버전처럼 구현하는게 좋을 것 같아요

2022-07-01 14:22 UTC, Eunyeol-Lucas commented on src/pages/App.tsx
> +              path="/guest/write/:postId/:iconId"
`/guest/write/:postId/` 이후에 `/guest/write/:postId/:iconId`로  params가 추가가 되는게 불필요하다고 생각이 들어요!
꽃에 대한 iconId를 우선 url에 기입하는게 어색하다 들기도 하고, params가 변경됨에 따라서 사용자가 꽃 선택 -> 편지 작성 -> 꽃 배치 로직에 따라서 이동했을 때, 꽃이 마음에 안들어서 뒤로가기를 해서 꽃을 변경하고 편지지로 이동하면 편지 내용이 초기화가 되어 사용자 경험 측면에 좋지 않을것 같아요. 아니면 편지 내용에 대한 상태관리가 추가가 되면 좋을 것 같습니다.
하지만 페이지 전환이 발생하지 않고  `/guest/write/:postId/`를 사용한다면 굳이 props 형식 또는 전역 상태관리가 필요하지 않을 것 같습니다.

2022-07-01 14:22 UTC, Eunyeol-Lucas commented on src/pages/GuestWrite.tsx
> +          >
너무 깔끔하게 로직을 잘 짜신 것 같습니다.
그런데 모바일에서는 터치로 드래그가 생각한 것과 같이 편하게 작동을 하는 데, 웹에서는 클릭으로 드래그를 시도한 뒤 클릭을 놓아야 원하는 위치로 이동이 가능하던데 의도하신 부분인가요?

2022-07-01 14:25 UTC, hanyoonseok commented
### 수정사항
- [x] 꽃 선택화면 UI 밸런스 수정
- [x] 꽃 초기 위치 중앙 세팅
- [x] 웹 버전에서도 드래깅이 자연스럽게 수정

### 비율에 대한 이슈는 해결하지 못 했습니다. min-height를 780으로 주게될 시 모바일 버전에서 화면이 780을 넘지 않는 경우 불필요한 스크롤이 발생하고 비율도 깨지게 됩니다 ㅜ.

2022-07-01 14:34 UTC, hanyoonseok commented on src/pages/App.tsx
> +              path="/guest/write/:postId/:iconId"
저도 이것에 대해서 생각해봤는데 일단 제 의도는
1. 꽃 선택 페이지(이하 select)와 편지작성/레이아웃(이하 write) 페이지가 서로 분리되어 있는 상태에서, select페이지에서 선택한 꽃의 정보(iconId)를 write 페이지로 전달할 수 있는 방법이 전역 상태관리 툴을 사용하지 않고는 localstorage 혹은 params밖에 없다고 생각했습니다. select 페이지도 write 페이지와 병합해버리면 write컴포넌트가 좀 무거워지긴 해도 해결 가능하긴 한데 그렇게 진행 해볼까요?

2022-07-01 14:34 UTC, hanyoonseok commented on src/pages/GuestWrite.tsx
> +          >
이 부분 수정했습니다!

2022-07-01 14:59 UTC, Eunyeol-Lucas commented on src/pages/App.tsx
> +              path="/guest/write/:postId/:iconId"
전역 상태관리를 사용하지 않는다면 조금 무겁더라도 동일한 페이지 내에 존재하는게 제 생객에는 좋을거 같아요 ㅎㅎ
write 와 select를 각각 컴포넌트로 구현해서 한 page에 배치하고 코드 스필리팅(상태에 따라서 동적 import 등)을 한다면 조금 괜찮지 않을까요?

2022-07-01 15:00 UTC, Eunyeol-Lucas commented
> 비율에 대한 이슈는 해결하지 못 했습니다. min-height를 780으로 주게될 시 모바일 버전에서 화면이 780을 넘지 않는 경우 불필요한 스크롤이 발생하고 비율도 깨지게 됩니다 ㅜ.

화면 비율은 저도 테스트하면서 적당한 위치를 찾아보겠습니다!

2022-07-01 16:55 UTC, hanyoonseok commented on src/pages/App.tsx
> +              path="/guest/write/:postId/:iconId"
select, write, layout 페이지 모두 병합 완료했습니다

2022-07-02 05:48 UTC, hanyoonseok commented
> * 꽃 선택하는 화면에서 꽃을 포함하는 div의 크기를 고정시키는게 어떨까요? 그리고 div간의 상하좌우 간격도 일정하면 좋을 것 같습니다.
> * 꽃 배치할 때 처음 위치를 왼쪽 상단이 아닌 중앙에 배치하는게 좋을 것 같습니다
> * pc버전에서 꽃 이동할 때 모바일 버전과는 다르게 잔상이 남는데 모바일 버전처럼 구현하는게 좋을 것 같아요

수정 완료했습니다

2022-07-02 11:27 UTC, merged